# DENTAKUのMakefile

TOPDIR := $(CURDIR)
include $(DEVKITPRO)/libctru/3ds_rules

TARGET := DENTAKU
SOURCES := $(CURDIR)/source
INCLUDES := $(CURDIR)/source

LIBS := -lctru -lm

include $(DEVKITARM)/base_rules
